version: '3.8'

services:
  app:
    image: todo-service-app
    container_name: todo-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    depends_on:
      - postgres
    env_file:
      - .env
#тут db не успевал создаваться, поэтому я сделал рестарт. Не знаю насколько это правильно, но это работает.
    restart: unless-stopped


  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres